// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: router.proto

package routerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrinoGatewayRouter_Route_FullMethodName = "/trino.gateway.v1.TrinoGatewayRouter/Route"
)

// TrinoGatewayRouterClient is the client API for TrinoGatewayRouter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TrinoGatewayRouter selects a backend routing group for each inbound Trino request.
type TrinoGatewayRouterClient interface {
	Route(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error)
}

type trinoGatewayRouterClient struct {
	cc grpc.ClientConnInterface
}

func NewTrinoGatewayRouterClient(cc grpc.ClientConnInterface) TrinoGatewayRouterClient {
	return &trinoGatewayRouterClient{cc}
}

func (c *trinoGatewayRouterClient) Route(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteResponse)
	err := c.cc.Invoke(ctx, TrinoGatewayRouter_Route_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrinoGatewayRouterServer is the server API for TrinoGatewayRouter service.
// All implementations must embed UnimplementedTrinoGatewayRouterServer
// for forward compatibility.
//
// TrinoGatewayRouter selects a backend routing group for each inbound Trino request.
type TrinoGatewayRouterServer interface {
	Route(context.Context, *RouteRequest) (*RouteResponse, error)
	mustEmbedUnimplementedTrinoGatewayRouterServer()
}

// UnimplementedTrinoGatewayRouterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrinoGatewayRouterServer struct{}

func (UnimplementedTrinoGatewayRouterServer) Route(context.Context, *RouteRequest) (*RouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Route not implemented")
}
func (UnimplementedTrinoGatewayRouterServer) mustEmbedUnimplementedTrinoGatewayRouterServer() {}
func (UnimplementedTrinoGatewayRouterServer) testEmbeddedByValue()                            {}

// UnsafeTrinoGatewayRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrinoGatewayRouterServer will
// result in compilation errors.
type UnsafeTrinoGatewayRouterServer interface {
	mustEmbedUnimplementedTrinoGatewayRouterServer()
}

func RegisterTrinoGatewayRouterServer(s grpc.ServiceRegistrar, srv TrinoGatewayRouterServer) {
	// If the following call panics, it indicates UnimplementedTrinoGatewayRouterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrinoGatewayRouter_ServiceDesc, srv)
}

func _TrinoGatewayRouter_Route_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrinoGatewayRouterServer).Route(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrinoGatewayRouter_Route_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrinoGatewayRouterServer).Route(ctx, req.(*RouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrinoGatewayRouter_ServiceDesc is the grpc.ServiceDesc for TrinoGatewayRouter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrinoGatewayRouter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trino.gateway.v1.TrinoGatewayRouter",
	HandlerType: (*TrinoGatewayRouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Route",
			Handler:    _TrinoGatewayRouter_Route_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "router.proto",
}
