// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: router.proto

package routerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RouteRequest mirrors RoutingGroupExternalBody.java.
// Fields that require trino-parser (queryType, tables, catalogs, schemas) are always
// empty strings/arrays in Go v1 because trino-parser is not embedded.
type RouteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Populated only when analyzeRequest=true; null otherwise.
	TrinoQueryProperties *TrinoQueryProperties `protobuf:"bytes,1,opt,name=trino_query_properties,json=trinoQueryProperties,proto3" json:"trino_query_properties,omitempty"`
	// Populated only when analyzeRequest=true; null otherwise.
	TrinoRequestUser *TrinoRequestUser `protobuf:"bytes,2,opt,name=trino_request_user,json=trinoRequestUser,proto3" json:"trino_request_user,omitempty"`
	// Always "application/json" in current implementation.
	ContentType string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// HttpServletRequest.getRemoteUser(); may be empty.
	RemoteUser string `protobuf:"bytes,4,opt,name=remote_user,json=remoteUser,proto3" json:"remote_user,omitempty"`
	// HTTP method: "POST", "GET", etc.
	Method string `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	// Path component only, e.g. "/v1/statement".
	RequestUri string `protobuf:"bytes,6,opt,name=request_uri,json=requestUri,proto3" json:"request_uri,omitempty"`
	// URL query string without leading "?"; empty if none.
	QueryString string `protobuf:"bytes,7,opt,name=query_string,json=queryString,proto3" json:"query_string,omitempty"`
	// Client IP address.
	RemoteAddr string `protobuf:"bytes,9,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	// Client hostname; may equal remote_addr if no reverse DNS.
	RemoteHost string `protobuf:"bytes,10,opt,name=remote_host,json=remoteHost,proto3" json:"remote_host,omitempty"`
	// URL and form parameters. Multi-valued params are comma-joined.
	ParameterMap map[string]string `protobuf:"bytes,11,rep,name=parameter_map,json=parameterMap,proto3" json:"parameter_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// X-Trino-Source header value (e.g. "airflow", "superset", "dbt").
	// Field number 12 matches the routing-service vendored proto (wire compat).
	TrinoSource string `protobuf:"bytes,12,opt,name=trino_source,json=trinoSource,proto3" json:"trino_source,omitempty"`
	// X-Trino-Client-Tags header value, pre-split on comma (trimmed, non-empty).
	// Field number 13 matches the routing-service vendored proto (wire compat).
	ClientTags    []string `protobuf:"bytes,13,rep,name=client_tags,json=clientTags,proto3" json:"client_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{0}
}

func (x *RouteRequest) GetTrinoQueryProperties() *TrinoQueryProperties {
	if x != nil {
		return x.TrinoQueryProperties
	}
	return nil
}

func (x *RouteRequest) GetTrinoRequestUser() *TrinoRequestUser {
	if x != nil {
		return x.TrinoRequestUser
	}
	return nil
}

func (x *RouteRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *RouteRequest) GetRemoteUser() string {
	if x != nil {
		return x.RemoteUser
	}
	return ""
}

func (x *RouteRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RouteRequest) GetRequestUri() string {
	if x != nil {
		return x.RequestUri
	}
	return ""
}

func (x *RouteRequest) GetQueryString() string {
	if x != nil {
		return x.QueryString
	}
	return ""
}

func (x *RouteRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *RouteRequest) GetRemoteHost() string {
	if x != nil {
		return x.RemoteHost
	}
	return ""
}

func (x *RouteRequest) GetParameterMap() map[string]string {
	if x != nil {
		return x.ParameterMap
	}
	return nil
}

func (x *RouteRequest) GetTrinoSource() string {
	if x != nil {
		return x.TrinoSource
	}
	return ""
}

func (x *RouteRequest) GetClientTags() []string {
	if x != nil {
		return x.ClientTags
	}
	return nil
}

// RouteResponse mirrors ExternalRouterResponse.java.
type RouteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Routing group name. Empty string or absent → use defaultRoutingGroup.
	RoutingGroup string `protobuf:"bytes,1,opt,name=routing_group,json=routingGroup,proto3" json:"routing_group,omitempty"`
	// Error messages. Non-empty + propagateErrors=true → HTTP 400 to client.
	Errors []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	// Headers to add or override on the proxied request. Keys in excludeHeaders are ignored.
	ExternalHeaders map[string]string `protobuf:"bytes,3,rep,name=external_headers,json=externalHeaders,proto3" json:"external_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{1}
}

func (x *RouteResponse) GetRoutingGroup() string {
	if x != nil {
		return x.RoutingGroup
	}
	return ""
}

func (x *RouteResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *RouteResponse) GetExternalHeaders() map[string]string {
	if x != nil {
		return x.ExternalHeaders
	}
	return nil
}

// TrinoQueryProperties mirrors TrinoQueryProperties.java.
// Fields requiring trino-parser are always empty in Go v1.
type TrinoQueryProperties struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw SQL text from request body.
	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	// Java AST class name (trino-parser required); always empty in Go v1.
	QueryType string `protobuf:"bytes,2,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
	// Resource group classification (trino-parser required); always empty in Go v1.
	ResourceGroupQueryType string `protobuf:"bytes,3,opt,name=resource_group_query_type,json=resourceGroupQueryType,proto3" json:"resource_group_query_type,omitempty"`
	// X-Trino-Catalog header value; null if absent.
	DefaultCatalog string `protobuf:"bytes,4,opt,name=default_catalog,json=defaultCatalog,proto3" json:"default_catalog,omitempty"`
	// X-Trino-Schema header value; null if absent.
	DefaultSchema string `protobuf:"bytes,5,opt,name=default_schema,json=defaultSchema,proto3" json:"default_schema,omitempty"`
	// Referenced catalog names (trino-parser required); always empty in Go v1.
	Catalogs []string `protobuf:"bytes,6,rep,name=catalogs,proto3" json:"catalogs,omitempty"`
	// Referenced schema names (trino-parser required); always empty in Go v1.
	Schemas []string `protobuf:"bytes,7,rep,name=schemas,proto3" json:"schemas,omitempty"`
	// "catalog.schema" strings (trino-parser required); always empty in Go v1.
	CatalogSchemas []string `protobuf:"bytes,8,rep,name=catalog_schemas,json=catalogSchemas,proto3" json:"catalog_schemas,omitempty"`
	// Fully-qualified table names (trino-parser required); always empty in Go v1.
	Tables []string `protobuf:"bytes,9,rep,name=tables,proto3" json:"tables,omitempty"`
	// true if method is POST.
	IsNewQuerySubmission bool `protobuf:"varint,10,opt,name=is_new_query_submission,json=isNewQuerySubmission,proto3" json:"is_new_query_submission,omitempty"`
	// Always false in Go v1 (no parser).
	IsQueryParsingSuccessful bool `protobuf:"varint,11,opt,name=is_query_parsing_successful,json=isQueryParsingSuccessful,proto3" json:"is_query_parsing_successful,omitempty"`
	// Always "trino-parser not available in Go v1".
	ErrorMessage  string `protobuf:"bytes,12,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrinoQueryProperties) Reset() {
	*x = TrinoQueryProperties{}
	mi := &file_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrinoQueryProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrinoQueryProperties) ProtoMessage() {}

func (x *TrinoQueryProperties) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrinoQueryProperties.ProtoReflect.Descriptor instead.
func (*TrinoQueryProperties) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{2}
}

func (x *TrinoQueryProperties) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *TrinoQueryProperties) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

func (x *TrinoQueryProperties) GetResourceGroupQueryType() string {
	if x != nil {
		return x.ResourceGroupQueryType
	}
	return ""
}

func (x *TrinoQueryProperties) GetDefaultCatalog() string {
	if x != nil {
		return x.DefaultCatalog
	}
	return ""
}

func (x *TrinoQueryProperties) GetDefaultSchema() string {
	if x != nil {
		return x.DefaultSchema
	}
	return ""
}

func (x *TrinoQueryProperties) GetCatalogs() []string {
	if x != nil {
		return x.Catalogs
	}
	return nil
}

func (x *TrinoQueryProperties) GetSchemas() []string {
	if x != nil {
		return x.Schemas
	}
	return nil
}

func (x *TrinoQueryProperties) GetCatalogSchemas() []string {
	if x != nil {
		return x.CatalogSchemas
	}
	return nil
}

func (x *TrinoQueryProperties) GetTables() []string {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *TrinoQueryProperties) GetIsNewQuerySubmission() bool {
	if x != nil {
		return x.IsNewQuerySubmission
	}
	return false
}

func (x *TrinoQueryProperties) GetIsQueryParsingSuccessful() bool {
	if x != nil {
		return x.IsQueryParsingSuccessful
	}
	return false
}

func (x *TrinoQueryProperties) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// TrinoRequestUser mirrors TrinoRequestUser.java.
type TrinoRequestUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username from X-Trino-User header.
	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// Additional user info; empty in Go v1.
	UserInfo      string `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrinoRequestUser) Reset() {
	*x = TrinoRequestUser{}
	mi := &file_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrinoRequestUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrinoRequestUser) ProtoMessage() {}

func (x *TrinoRequestUser) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrinoRequestUser.ProtoReflect.Descriptor instead.
func (*TrinoRequestUser) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{3}
}

func (x *TrinoRequestUser) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *TrinoRequestUser) GetUserInfo() string {
	if x != nil {
		return x.UserInfo
	}
	return ""
}

var File_router_proto protoreflect.FileDescriptor

const file_router_proto_rawDesc = "" +
	"\n" +
	"\frouter.proto\x12\x10trino.gateway.v1\"\xfc\x04\n" +
	"\fRouteRequest\x12\\\n" +
	"\x16trino_query_properties\x18\x01 \x01(\v2&.trino.gateway.v1.TrinoQueryPropertiesR\x14trinoQueryProperties\x12P\n" +
	"\x12trino_request_user\x18\x02 \x01(\v2\".trino.gateway.v1.TrinoRequestUserR\x10trinoRequestUser\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1f\n" +
	"\vremote_user\x18\x04 \x01(\tR\n" +
	"remoteUser\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x1f\n" +
	"\vrequest_uri\x18\x06 \x01(\tR\n" +
	"requestUri\x12!\n" +
	"\fquery_string\x18\a \x01(\tR\vqueryString\x12\x1f\n" +
	"\vremote_addr\x18\t \x01(\tR\n" +
	"remoteAddr\x12\x1f\n" +
	"\vremote_host\x18\n" +
	" \x01(\tR\n" +
	"remoteHost\x12U\n" +
	"\rparameter_map\x18\v \x03(\v20.trino.gateway.v1.RouteRequest.ParameterMapEntryR\fparameterMap\x12!\n" +
	"\ftrino_source\x18\f \x01(\tR\vtrinoSource\x12\x1f\n" +
	"\vclient_tags\x18\r \x03(\tR\n" +
	"clientTags\x1a?\n" +
	"\x11ParameterMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf1\x01\n" +
	"\rRouteResponse\x12#\n" +
	"\rrouting_group\x18\x01 \x01(\tR\froutingGroup\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\x12_\n" +
	"\x10external_headers\x18\x03 \x03(\v24.trino.gateway.v1.RouteResponse.ExternalHeadersEntryR\x0fexternalHeaders\x1aB\n" +
	"\x14ExternalHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x03\n" +
	"\x14TrinoQueryProperties\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"query_type\x18\x02 \x01(\tR\tqueryType\x129\n" +
	"\x19resource_group_query_type\x18\x03 \x01(\tR\x16resourceGroupQueryType\x12'\n" +
	"\x0fdefault_catalog\x18\x04 \x01(\tR\x0edefaultCatalog\x12%\n" +
	"\x0edefault_schema\x18\x05 \x01(\tR\rdefaultSchema\x12\x1a\n" +
	"\bcatalogs\x18\x06 \x03(\tR\bcatalogs\x12\x18\n" +
	"\aschemas\x18\a \x03(\tR\aschemas\x12'\n" +
	"\x0fcatalog_schemas\x18\b \x03(\tR\x0ecatalogSchemas\x12\x16\n" +
	"\x06tables\x18\t \x03(\tR\x06tables\x125\n" +
	"\x17is_new_query_submission\x18\n" +
	" \x01(\bR\x14isNewQuerySubmission\x12=\n" +
	"\x1bis_query_parsing_successful\x18\v \x01(\bR\x18isQueryParsingSuccessful\x12#\n" +
	"\rerror_message\x18\f \x01(\tR\ferrorMessage\"C\n" +
	"\x10TrinoRequestUser\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1b\n" +
	"\tuser_info\x18\x02 \x01(\tR\buserInfo2^\n" +
	"\x12TrinoGatewayRouter\x12H\n" +
	"\x05Route\x12\x1e.trino.gateway.v1.RouteRequest\x1a\x1f.trino.gateway.v1.RouteResponseB<Z:github.com/hclincode/trino-goway/internal/routing/routerpbb\x06proto3"

var (
	file_router_proto_rawDescOnce sync.Once
	file_router_proto_rawDescData []byte
)

func file_router_proto_rawDescGZIP() []byte {
	file_router_proto_rawDescOnce.Do(func() {
		file_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_router_proto_rawDesc), len(file_router_proto_rawDesc)))
	})
	return file_router_proto_rawDescData
}

var file_router_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_router_proto_goTypes = []any{
	(*RouteRequest)(nil),         // 0: trino.gateway.v1.RouteRequest
	(*RouteResponse)(nil),        // 1: trino.gateway.v1.RouteResponse
	(*TrinoQueryProperties)(nil), // 2: trino.gateway.v1.TrinoQueryProperties
	(*TrinoRequestUser)(nil),     // 3: trino.gateway.v1.TrinoRequestUser
	nil,                          // 4: trino.gateway.v1.RouteRequest.ParameterMapEntry
	nil,                          // 5: trino.gateway.v1.RouteResponse.ExternalHeadersEntry
}
var file_router_proto_depIdxs = []int32{
	2, // 0: trino.gateway.v1.RouteRequest.trino_query_properties:type_name -> trino.gateway.v1.TrinoQueryProperties
	3, // 1: trino.gateway.v1.RouteRequest.trino_request_user:type_name -> trino.gateway.v1.TrinoRequestUser
	4, // 2: trino.gateway.v1.RouteRequest.parameter_map:type_name -> trino.gateway.v1.RouteRequest.ParameterMapEntry
	5, // 3: trino.gateway.v1.RouteResponse.external_headers:type_name -> trino.gateway.v1.RouteResponse.ExternalHeadersEntry
	0, // 4: trino.gateway.v1.TrinoGatewayRouter.Route:input_type -> trino.gateway.v1.RouteRequest
	1, // 5: trino.gateway.v1.TrinoGatewayRouter.Route:output_type -> trino.gateway.v1.RouteResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_router_proto_init() }
func file_router_proto_init() {
	if File_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_router_proto_rawDesc), len(file_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_router_proto_goTypes,
		DependencyIndexes: file_router_proto_depIdxs,
		MessageInfos:      file_router_proto_msgTypes,
	}.Build()
	File_router_proto = out.File
	file_router_proto_goTypes = nil
	file_router_proto_depIdxs = nil
}
