// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: admin.proto

package routingadmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DisableMethodRequest names the method type to disable, e.g. "expr" or "script".
type DisableMethodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableMethodRequest) Reset() {
	*x = DisableMethodRequest{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableMethodRequest) ProtoMessage() {}

func (x *DisableMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableMethodRequest.ProtoReflect.Descriptor instead.
func (*DisableMethodRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

func (x *DisableMethodRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DisableMethodResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ok is true when the call was accepted. It is true even for an unknown type
	// (the operation is idempotent / best-effort); inspect message for detail.
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// message is a human-readable result, e.g. "disabled" or "unknown method type".
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// disabled is the full set of disabled method types after the operation.
	Disabled      []string `protobuf:"bytes,3,rep,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableMethodResponse) Reset() {
	*x = DisableMethodResponse{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableMethodResponse) ProtoMessage() {}

func (x *DisableMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableMethodResponse.ProtoReflect.Descriptor instead.
func (*DisableMethodResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *DisableMethodResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DisableMethodResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DisableMethodResponse) GetDisabled() []string {
	if x != nil {
		return x.Disabled
	}
	return nil
}

// EnableMethodRequest names the method type to re-enable.
type EnableMethodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableMethodRequest) Reset() {
	*x = EnableMethodRequest{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableMethodRequest) ProtoMessage() {}

func (x *EnableMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableMethodRequest.ProtoReflect.Descriptor instead.
func (*EnableMethodRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

func (x *EnableMethodRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type EnableMethodResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Ok      bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// disabled is the full set of disabled method types after the operation.
	Disabled      []string `protobuf:"bytes,3,rep,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableMethodResponse) Reset() {
	*x = EnableMethodResponse{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableMethodResponse) ProtoMessage() {}

func (x *EnableMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableMethodResponse.ProtoReflect.Descriptor instead.
func (*EnableMethodResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *EnableMethodResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *EnableMethodResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EnableMethodResponse) GetDisabled() []string {
	if x != nil {
		return x.Disabled
	}
	return nil
}

type ListDisabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDisabledRequest) Reset() {
	*x = ListDisabledRequest{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDisabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDisabledRequest) ProtoMessage() {}

func (x *ListDisabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDisabledRequest.ProtoReflect.Descriptor instead.
func (*ListDisabledRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

type ListDisabledResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// disabled is the type names of all currently-disabled methods.
	Disabled      []string `protobuf:"bytes,1,rep,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDisabledResponse) Reset() {
	*x = ListDisabledResponse{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDisabledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDisabledResponse) ProtoMessage() {}

func (x *ListDisabledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDisabledResponse.ProtoReflect.Descriptor instead.
func (*ListDisabledResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListDisabledResponse) GetDisabled() []string {
	if x != nil {
		return x.Disabled
	}
	return nil
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x12\x10trino.gateway.v1\"*\n" +
	"\x14DisableMethodRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"]\n" +
	"\x15DisableMethodResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bdisabled\x18\x03 \x03(\tR\bdisabled\")\n" +
	"\x13EnableMethodRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"\\\n" +
	"\x14EnableMethodResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bdisabled\x18\x03 \x03(\tR\bdisabled\"\x15\n" +
	"\x13ListDisabledRequest\"2\n" +
	"\x14ListDisabledResponse\x12\x1a\n" +
	"\bdisabled\x18\x01 \x03(\tR\bdisabled2\xb5\x02\n" +
	"\x13RoutingServiceAdmin\x12`\n" +
	"\rDisableMethod\x12&.trino.gateway.v1.DisableMethodRequest\x1a'.trino.gateway.v1.DisableMethodResponse\x12]\n" +
	"\fEnableMethod\x12%.trino.gateway.v1.EnableMethodRequest\x1a&.trino.gateway.v1.EnableMethodResponse\x12]\n" +
	"\fListDisabled\x12%.trino.gateway.v1.ListDisabledRequest\x1a&.trino.gateway.v1.ListDisabledResponseB;Z9github.com/hclincode/trino-goway-routing-service/routerpbb\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_admin_proto_goTypes = []any{
	(*DisableMethodRequest)(nil),  // 0: trino.gateway.v1.DisableMethodRequest
	(*DisableMethodResponse)(nil), // 1: trino.gateway.v1.DisableMethodResponse
	(*EnableMethodRequest)(nil),   // 2: trino.gateway.v1.EnableMethodRequest
	(*EnableMethodResponse)(nil),  // 3: trino.gateway.v1.EnableMethodResponse
	(*ListDisabledRequest)(nil),   // 4: trino.gateway.v1.ListDisabledRequest
	(*ListDisabledResponse)(nil),  // 5: trino.gateway.v1.ListDisabledResponse
}
var file_admin_proto_depIdxs = []int32{
	0, // 0: trino.gateway.v1.RoutingServiceAdmin.DisableMethod:input_type -> trino.gateway.v1.DisableMethodRequest
	2, // 1: trino.gateway.v1.RoutingServiceAdmin.EnableMethod:input_type -> trino.gateway.v1.EnableMethodRequest
	4, // 2: trino.gateway.v1.RoutingServiceAdmin.ListDisabled:input_type -> trino.gateway.v1.ListDisabledRequest
	1, // 3: trino.gateway.v1.RoutingServiceAdmin.DisableMethod:output_type -> trino.gateway.v1.DisableMethodResponse
	3, // 4: trino.gateway.v1.RoutingServiceAdmin.EnableMethod:output_type -> trino.gateway.v1.EnableMethodResponse
	5, // 5: trino.gateway.v1.RoutingServiceAdmin.ListDisabled:output_type -> trino.gateway.v1.ListDisabledResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
