// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: admin.proto

package routingadmin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoutingServiceAdmin_DisableMethod_FullMethodName = "/trino.gateway.v1.RoutingServiceAdmin/DisableMethod"
	RoutingServiceAdmin_EnableMethod_FullMethodName  = "/trino.gateway.v1.RoutingServiceAdmin/EnableMethod"
	RoutingServiceAdmin_ListDisabled_FullMethodName  = "/trino.gateway.v1.RoutingServiceAdmin/ListDisabled"
)

// RoutingServiceAdminClient is the client API for RoutingServiceAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RoutingServiceAdmin is the runtime control-plane for the routing-service.
// It exposes the pipeline kill-switch so a platform operator can disable or
// re-enable a routing method at runtime without a restart — changes take
// effect on the very next Route call (atomic, sub-millisecond propagation).
//
// SECURITY (Phase 1): this service has NO authentication. It must be served on
// a separate, firewalled admin listener (cfg.AdminAddr) reachable only by
// platform operators. Phase 2 adds mTLS + a scoped admin credential; see the
// routing-service PRD backlog.
type RoutingServiceAdminClient interface {
	// DisableMethod marks the named routing method disabled. The pipeline skips
	// it on the next Route call; the method's compiled program stays resident so
	// EnableMethod is instantaneous. Disabling an unknown type is a no-op.
	DisableMethod(ctx context.Context, in *DisableMethodRequest, opts ...grpc.CallOption) (*DisableMethodResponse, error)
	// EnableMethod re-enables a previously-disabled method. Enabling a method
	// that is not disabled (or is unknown) is a no-op.
	EnableMethod(ctx context.Context, in *EnableMethodRequest, opts ...grpc.CallOption) (*EnableMethodResponse, error)
	// ListDisabled returns the type names of all currently-disabled methods.
	ListDisabled(ctx context.Context, in *ListDisabledRequest, opts ...grpc.CallOption) (*ListDisabledResponse, error)
}

type routingServiceAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutingServiceAdminClient(cc grpc.ClientConnInterface) RoutingServiceAdminClient {
	return &routingServiceAdminClient{cc}
}

func (c *routingServiceAdminClient) DisableMethod(ctx context.Context, in *DisableMethodRequest, opts ...grpc.CallOption) (*DisableMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableMethodResponse)
	err := c.cc.Invoke(ctx, RoutingServiceAdmin_DisableMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceAdminClient) EnableMethod(ctx context.Context, in *EnableMethodRequest, opts ...grpc.CallOption) (*EnableMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableMethodResponse)
	err := c.cc.Invoke(ctx, RoutingServiceAdmin_EnableMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceAdminClient) ListDisabled(ctx context.Context, in *ListDisabledRequest, opts ...grpc.CallOption) (*ListDisabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDisabledResponse)
	err := c.cc.Invoke(ctx, RoutingServiceAdmin_ListDisabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutingServiceAdminServer is the server API for RoutingServiceAdmin service.
// All implementations must embed UnimplementedRoutingServiceAdminServer
// for forward compatibility.
//
// RoutingServiceAdmin is the runtime control-plane for the routing-service.
// It exposes the pipeline kill-switch so a platform operator can disable or
// re-enable a routing method at runtime without a restart — changes take
// effect on the very next Route call (atomic, sub-millisecond propagation).
//
// SECURITY (Phase 1): this service has NO authentication. It must be served on
// a separate, firewalled admin listener (cfg.AdminAddr) reachable only by
// platform operators. Phase 2 adds mTLS + a scoped admin credential; see the
// routing-service PRD backlog.
type RoutingServiceAdminServer interface {
	// DisableMethod marks the named routing method disabled. The pipeline skips
	// it on the next Route call; the method's compiled program stays resident so
	// EnableMethod is instantaneous. Disabling an unknown type is a no-op.
	DisableMethod(context.Context, *DisableMethodRequest) (*DisableMethodResponse, error)
	// EnableMethod re-enables a previously-disabled method. Enabling a method
	// that is not disabled (or is unknown) is a no-op.
	EnableMethod(context.Context, *EnableMethodRequest) (*EnableMethodResponse, error)
	// ListDisabled returns the type names of all currently-disabled methods.
	ListDisabled(context.Context, *ListDisabledRequest) (*ListDisabledResponse, error)
	mustEmbedUnimplementedRoutingServiceAdminServer()
}

// UnimplementedRoutingServiceAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoutingServiceAdminServer struct{}

func (UnimplementedRoutingServiceAdminServer) DisableMethod(context.Context, *DisableMethodRequest) (*DisableMethodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableMethod not implemented")
}
func (UnimplementedRoutingServiceAdminServer) EnableMethod(context.Context, *EnableMethodRequest) (*EnableMethodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableMethod not implemented")
}
func (UnimplementedRoutingServiceAdminServer) ListDisabled(context.Context, *ListDisabledRequest) (*ListDisabledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDisabled not implemented")
}
func (UnimplementedRoutingServiceAdminServer) mustEmbedUnimplementedRoutingServiceAdminServer() {}
func (UnimplementedRoutingServiceAdminServer) testEmbeddedByValue()                             {}

// UnsafeRoutingServiceAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutingServiceAdminServer will
// result in compilation errors.
type UnsafeRoutingServiceAdminServer interface {
	mustEmbedUnimplementedRoutingServiceAdminServer()
}

func RegisterRoutingServiceAdminServer(s grpc.ServiceRegistrar, srv RoutingServiceAdminServer) {
	// If the following call panics, it indicates UnimplementedRoutingServiceAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoutingServiceAdmin_ServiceDesc, srv)
}

func _RoutingServiceAdmin_DisableMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceAdminServer).DisableMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingServiceAdmin_DisableMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceAdminServer).DisableMethod(ctx, req.(*DisableMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingServiceAdmin_EnableMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceAdminServer).EnableMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingServiceAdmin_EnableMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceAdminServer).EnableMethod(ctx, req.(*EnableMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingServiceAdmin_ListDisabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDisabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceAdminServer).ListDisabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingServiceAdmin_ListDisabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceAdminServer).ListDisabled(ctx, req.(*ListDisabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoutingServiceAdmin_ServiceDesc is the grpc.ServiceDesc for RoutingServiceAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoutingServiceAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trino.gateway.v1.RoutingServiceAdmin",
	HandlerType: (*RoutingServiceAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DisableMethod",
			Handler:    _RoutingServiceAdmin_DisableMethod_Handler,
		},
		{
			MethodName: "EnableMethod",
			Handler:    _RoutingServiceAdmin_EnableMethod_Handler,
		},
		{
			MethodName: "ListDisabled",
			Handler:    _RoutingServiceAdmin_ListDisabled_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
