package testutil

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"
)

// TrinoFake is a richer fake Trino backend that handles the full statement protocol
// including sticky-routing GETs, HEAD probes, and KILL QUERY (DELETE) requests.
type TrinoFake struct {
	// URL is the base URL of the fake Trino server.
	URL string

	server *httptest.Server
	seq    atomic.Uint64

	mu             sync.Mutex
	queryIDs       []string
	requestBody    map[string][]byte
	requestHeaders map[string]http.Header
	hitCount       map[string]int
	headProbes     map[string]int
	cancellations  []string
	starting       bool
}

// NewTrinoFake creates a fake Trino backend httptest.Server with the full statement
// protocol surface needed by E2E and proxy seam tests. Registers t.Cleanup to close
// the server.
func NewTrinoFake(t testing.TB) *TrinoFake {
	t.Helper()

	f := &TrinoFake{
		requestBody:    make(map[string][]byte),
		requestHeaders: make(map[string]http.Header),
		hitCount:       make(map[string]int),
		headProbes:     make(map[string]int),
	}

	mux := http.NewServeMux()
	mux.HandleFunc("/", f.dispatch)

	f.server = httptest.NewServer(mux)
	f.URL = f.server.URL

	t.Cleanup(f.server.Close)

	return f
}

// QueryIDs returns all queryIds generated by POST /v1/statement in order.
func (f *TrinoFake) QueryIDs() []string {
	f.mu.Lock()
	defer f.mu.Unlock()

	out := make([]string, len(f.queryIDs))
	copy(out, f.queryIDs)
	return out
}

// HitCount returns the number of GET /v1/query/<queryId> requests received.
func (f *TrinoFake) HitCount(queryID string) int {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.hitCount[queryID]
}

// HeadProbes returns the number of HEAD /v1/query/<queryId> requests received.
func (f *TrinoFake) HeadProbes(queryID string) int {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.headProbes[queryID]
}

// Cancellations returns the queryIds that received a DELETE /v1/query/<queryId>.
func (f *TrinoFake) Cancellations() []string {
	f.mu.Lock()
	defer f.mu.Unlock()

	out := make([]string, len(f.cancellations))
	copy(out, f.cancellations)
	return out
}

// ReceivedHeaders returns the HTTP headers from the POST /v1/statement that
// created the given queryId.
func (f *TrinoFake) ReceivedHeaders(queryID string) http.Header {
	f.mu.Lock()
	defer f.mu.Unlock()

	h, ok := f.requestHeaders[queryID]
	if !ok {
		return nil
	}
	return h.Clone()
}

// SetStarting toggles whether /v1/info reports the backend as starting.
func (f *TrinoFake) SetStarting(v bool) {
	f.mu.Lock()
	f.starting = v
	f.mu.Unlock()
}

func (f *TrinoFake) dispatch(w http.ResponseWriter, r *http.Request) {
	path := r.URL.Path

	switch {
	case path == "/v1/info" && r.Method == http.MethodGet:
		f.handleInfo(w, r)
	case path == "/v1/statement" && r.Method == http.MethodPost:
		f.handleStatement(w, r)
	case strings.HasPrefix(path, "/v1/query/"):
		f.handleQuery(w, r)
	default:
		http.NotFound(w, r)
	}
}

func (f *TrinoFake) handleInfo(w http.ResponseWriter, _ *http.Request) {
	f.mu.Lock()
	starting := f.starting
	f.mu.Unlock()

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	if starting {
		_, _ = fmt.Fprint(w, `{"starting":true}`)
		return
	}
	_, _ = fmt.Fprint(w, `{"starting":false,"uptime":"0.00s","nodeVersion":{"version":"481"}}`)
}

func (f *TrinoFake) handleStatement(w http.ResponseWriter, r *http.Request) {
	queryID := f.newQueryID()

	body := make([]byte, 0, 1024)
	if r.Body != nil {
		buf := make([]byte, 1024)
		for {
			n, err := r.Body.Read(buf)
			if n > 0 {
				body = append(body, buf[:n]...)
			}
			if err != nil {
				break
			}
		}
	}

	headers := r.Header.Clone()

	f.mu.Lock()
	f.queryIDs = append(f.queryIDs, queryID)
	f.requestBody[queryID] = body
	f.requestHeaders[queryID] = headers
	f.mu.Unlock()

	resp := map[string]any{
		"id":      queryID,
		"nextUri": "http://" + r.Host + "/v1/query/" + queryID + "/1",
		"infoUri": "http://" + r.Host + "/v1/queryinfo/" + queryID,
		"stats": map[string]any{
			"state":              "QUEUED",
			"queued":             true,
			"scheduled":          false,
			"nodes":              0,
			"totalSplits":        0,
			"queuedSplits":       0,
			"runningSplits":      0,
			"completedSplits":    0,
			"cpuTimeMillis":      0,
			"wallTimeMillis":     0,
			"queuedTimeMillis":   0,
			"elapsedTimeMillis":  0,
			"processedRows":      0,
			"processedBytes":     0,
			"peakMemoryBytes":    0,
			"spilledBytes":       0,
		},
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(w).Encode(resp)
}

func (f *TrinoFake) handleQuery(w http.ResponseWriter, r *http.Request) {
	queryID := extractQueryID(r.URL.Path)

	switch r.Method {
	case http.MethodGet:
		f.mu.Lock()
		f.hitCount[queryID]++
		f.mu.Unlock()

		resp := map[string]any{
			"id": queryID,
			"stats": map[string]any{
				"state":     "FINISHED",
				"queued":    false,
				"scheduled": false,
			},
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(resp)

	case http.MethodHead:
		f.mu.Lock()
		f.headProbes[queryID]++
		_, known := f.requestBody[queryID]
		f.mu.Unlock()

		if known {
			w.WriteHeader(http.StatusOK)
			return
		}
		w.WriteHeader(http.StatusNotFound)

	case http.MethodDelete:
		f.mu.Lock()
		f.cancellations = append(f.cancellations, queryID)
		f.mu.Unlock()

		w.WriteHeader(http.StatusOK)

	default:
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
	}
}

// extractQueryID returns the queryId segment that immediately follows /v1/query/.
func extractQueryID(path string) string {
	rest := strings.TrimPrefix(path, "/v1/query/")
	if i := strings.IndexByte(rest, '/'); i >= 0 {
		return rest[:i]
	}
	return rest
}

func (f *TrinoFake) newQueryID() string {
	ms := time.Now().UnixMilli()
	seq := f.seq.Add(1)

	var randBytes [2]byte
	_, _ = rand.Read(randBytes[:])

	return fmt.Sprintf("%d_%d_%s_trino", ms, seq, hex.EncodeToString(randBytes[:]))
}
